<?php
$columns = [
    'nickname' => 'email', //Attende?
    'first_name' => '',
    'last_name' => '',
    'description' => '',
    'locale' => '',
    'wp_capabilities' => '', //Participant or attende
    'rm_activation_time' => '',
    'rm_activation_hash' => '',
    'firstnametm' => 'firstname', //Team manager
    'lastnametm' => 'lastname',
    'mobilephonetm' => 'phone',
    'firstnameoc' => 'firstname', //Owner
    'lastnameoc' => 'lastname',
    'mobilephoneoc' => 'phone',
    'emailoc' => 'email',
    'boatname' => 'name',// Boat
    'boatbrand' => 'brand',
    'boatmodel' => 'model',
    'boatloa' => 'loa',
    'boatbeam' => 'beam',
    'boatdraft' => 'draft',
    'boatsailnumber' => 'sail_number',
    'boatarrivalstp' => 'date_arrival',
    'boatdeparturemi' => 'date_departure',
    'boatclass' => 'class',
    'uploadboatdocs' => '', //Boat docs
    'firstnamebc' => 'firstname', //Captain
    'lastnamebc' => 'lastname',
    'mobilephonebc' => 'phone',
    'emailbc' => 'email',
    'bringownrib' => '',// Rib (zodiac)
    'namerib' => 'name',
    'loarib' => 'loa',
    'beamrib' => 'beam',
    'ribarrivalstp' => 'date_arrival', // Boat
    'departureribmi' => 'date_departure',
    'uploadribdocs' => 'docs',
    'parkingrequired' => '',
    'licenseparking' => '',
    'owncontainer' => '',
    'owncontainersize' => 'container_size',
    'owndiverexists' => '',// Diver
    'firstnamedv' => 'firstname',
    'lastnamedv' => 'lastname',
    'divercertificate' => 'certificate',//Diver docs
    'externaldiverreq' => 'external_diver_required',
    'companyaddress' => 'company_address',
    'companyname'  => 'company_name',
    'companyvat' => 'company_vat',
    'companyzipcity' => 'company_zip_city'
];

$columnsAttendants = [
    'first_name' => 'firstname',
    'last_name' => 'lastname',
    'job-title' => 'position', //Test editor
    'nickname' => 'email',
    'outlet' => 'media', //Testoutlet
    'positiontyp' => 'media_department', //Editorial
    'subphone' => 'phone',
    'subs-category' => 'type_id',//Testoutlet
    'typeofmagazine' => 'media_category', //Nautical
];
